# Generated by Django 6.1 on 2026-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='event_type',
            field=models.CharField(choices=[('tool_call', 'Tool Call'), ('final_reply', 'Final Reply'), ('manager', 'Manager'), ('tool_result', 'Tool Result'), ('risk_agent', 'Risk Agent'), ('support', 'Support')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User')], max_length=20),
        ),
    ]
