# Generated by Django 6.1 on 2026-08-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_stock',
            new_name='in_stock',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('dispachted', 'Dispatched'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
