# Generated by Django 6.1 on 2026-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_refundrequest_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('dispachted', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
