# Generated by Django 6.1 on 2026-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_alter_refundrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('dispachted', 'Dispatched'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
