# Generated by Django 6.1 on 2026-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_refundrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('dispachted', 'Dispatched')], default='pending', max_length=100),
        ),
    ]
